### PR TITLE
Correct the nats.machines override code to generate the correct config

### PR DESCRIPTION
**Pull request by andrew-edgar**
The original PR I created did not work when creating the set of routes.   

This new update should fix the override of nats.machines.

### CODE REVIEW

**Comment by jrussett** [comment]
Hi @andrew-edgar 

The changes look great so far; thank you for correcting this behavior. 

❓ Could you please add some template tests ([nats](https://github.com/cloudfoundry/nats-release/blob/develop/spec/nats/nats_config_spec.rb), [nats-tls](https://github.com/cloudfoundry/nats-release/blob/develop/spec/nats-tls/nats_tls_config_spec.rb)) to demonstrate and exercise this behavior?

Thanks!
@jrussett && @ameowlia

**Comment by andrew-edgar** [comment]
@jrussett can you provide me with links / examples of existing template tests?  I have never seen any tests like that and where are they in the repo?

**Comment by ameowlia** [comment]
@andrew-edgar you can see the links for each job in @jrussett 's comment above.

**Comment by andrew-edgar** [comment]
I have added 2 tests.  I also fixed the existing 4 tests that were failing before I even started.   let me know what you think.

Thanks

**Comment by kkburr** [comment]
@Benjamintf1 and I were fixing a broken pipeline today and did not realize it was related to this PR. We pushed up a fix ourselves before discovering that this exists. https://github.com/cloudfoundry/nats-release/commit/f50081b91a7f78b76d1e548ef6a6fe1353f60722

@andrew-edgar if it's alright with you we'd like to close this PR.

**Comment by andrew-edgar** [comment]
SO you said to me in the slacks thread I had more test coverage.  Did you add my tests to your commit?

**Comment by reneighbor** [comment]
@andrew-edgar Thank you so much for submitting this PR. Your work has passed though our CI and will be part of the next nats-release.

**Pull request closed without merging**
