### PR TITLE
Escape nats passwords depending on context

### PR DESCRIPTION
**Pull request by ericpromislow**
# Don't accept this yet.

I want to discuss this with the capi team first.

Also, I used double-quoted strings in the ruby code as backslashes are
ambiguous in single-quoted strings.

### CODE REVIEW

**Comment by ericpromislow** [comment]
I just did some more testing. It turns out that `\"` doesn't escape the following quote in the apcera lexer, leading to a slew of "Authorization Errors". Might be best to tell users to just use alphanumerics in their nats password, given that the file format apcera/gnatsd isn't a standard. I skimmed through the lex code, and saw something that looked like it does backslash-escaping, but testing suggests it doesn't work the way I thought it did.

**Comment by ericpromislow** [comment]
... reading further, the apcera lexer recognizes backslashes in strings, but it doesn't actually perform backslash-escaping. So `\"` won't end a string, but the parser doesn't replace `\"` with `"`, so if you're trying to do something like verify credentials, you'll fail.

**Comment by dsabeti** [comment]
Hey @ericpromislow. Could you explain a little bit about the goal of this change? Did you want to allow non-alphanumeric characters in the nats password? If so, does it look like that's possible now?

**Comment by ericpromislow** [comment]
I want to allow as many characters as possible in the nats password. As https://github.com/cloudfoundry/nats-release/blob/5aa8ec15d272f70282aac3acfe77067d32e2d30e/jobs/nats/spec#L32 doesn't specify a lexical format, I assume any ASCII characters are allowed.

Currently, without the PR, double-quotes in the password field will most likely cause a syntax error in the `nats.conf` config field, triggering a pre-start job failure. Any clients that construct a string URI to connect with nats, including the `nats-route` part of the config, need to percent-escape problematic characters.

Given the above, I'd say without this PR the following characters are accepted:

` A-Z a-z 0-9 - . _ ~ ! $ & ' ( ) * + , ; = : ` [1]

So, many ASCII non-alnums are supported, but not all of them.

[1] https://tools.ietf.org/html/rfc3986#section-3.2.1

**Comment by ericpromislow** [comment]
Verified that the individual strings in the generated routes array do not need to be quoted, as the nats config parser supports bare strings. So the only change needed is to `URI.escape` the password field.

**Comment by dsabeti** [comment]
Hey @ericpromislow. I think it makes sense to want to allow more characters, but it's pretty simple to configure a secure nats password without this change. Adding a feature like this is not a high priority for the Release Integration team, unless there's an important reason to bring this into the backlog. Do you have any thoughts on the importance of this change?

**Comment by ericpromislow** [comment]
Given that some non-alnums are currently supported, but not others, I would ignore my proposed changes and just document the character set in `jobs/nats/spec` for passwords, namely alnums and any of `. - _` and leave it at that.   After all this, I'm willing to cut my bank some slack for restricting my password  to alnums.

**Comment by dsabeti** [comment]
Thanks @ericpromislow. I'm going to go ahead and close this PR. We'll try to document the allowed character set.

**Pull request closed without merging**
