### PR TITLE
Make nats forwarder bosh 2.0 using links + bosh lite example.

### PR DESCRIPTION
**Pull request by shinji62**
Make stream Forwarder bosh.2 ish
Added manifest example for bosh-lite

### CODE REVIEW

**Comment by shinji62** [comment]
@robdimsdale any thought on this PR ?

**Comment by Amit-PivotalLabs** [comment]
Hi @shinji62 

This appears to be backwards incompatible.  It will only work with BOSH 2.0 manifests, but we intend this release to still work with CF deployments, which are in the long process of switching over.  All switching will require backwards-compatible changes to the job specs and templates to support 1.0 and 2.0 for a period of time.

**Comment by shinji62** [comment]
Ok, why links are already implemented into the nats job  ?

**Comment by Amit-PivotalLabs** [comment]
Rob Dimsdale can let you know more details. But we will need to either
revert those changes or make them backwards compatible before moving
forward on our "extract-nats-release" track.

Cheers,
Amit

**Comment by robdimsdale** [comment]
Our plan is to make nats-release backwards compatible before bumping it in cf-release - the breaking changes (adding links without a fallback mechanism) were to facilitate us moving forward with testing the extraction of nats-release in a standalone manner.

**Comment by shinji62** [comment]
Ok got it :) @robdimsdale and @Amit-PivotalLabs I guess I will wait.

**Comment by Amit-PivotalLabs** [comment]
Thanks @shinji62, this PR will be a useful reference.  I'm going to close this PR for now.  We will come back and look at this PR when we schedule work to BOSH 2.0-ify all the things.

**Pull request closed without merging**
