### PR TITLE
Move setup of the nats and stream-forwarder log directories to before their first use.

### PR DESCRIPTION
**Pull request by andreas-kupries**

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
Thanks @andreas-kupries 

Can you expand on what you mean by "first use"?  The $LOG_DIR is not being used before the `mkdir` unless I'm mistaken.  Perhaps it's confusing because something is written to `/var/vcap/sys/log/nats_ctl.log` which kinda looks like the LOG_DIR which is `/var/vcap/sys/log/nats`?

**Comment by andreas-kupries** [comment]
Using file `https://jira.hpcloud.net/browse/HCF-786` as example.

Line 20 (before the patch) moves a file into the LOG_DIR.
The LOG_DIR is then created in line 23.

After the patch the creation is done in line 5 and the move in line 22.

The other files has an equivalent issue.

**Comment by Amit-PivotalLabs** [comment]
Ah, I'm sorry, totally right.

**Comment by DennisDenuto** [comment]
LGTM

**Pull request merged**
